"""Add RemoteService table

Revision ID: 0cd62d9cc944
Revises: 6357392de6c9
Create Date: 2026-02-12 12:03:23.211789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd62d9cc944'
down_revision: Union[str, None] = '6357392de6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('flash_update', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['machines.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remote_service_id'), 'remote_service', ['id'], unique=False)
    op.create_index(op.f('ix_remote_service_serial_number'), 'remote_service', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remote_service_serial_number'), table_name='remote_service')
    op.drop_index(op.f('ix_remote_service_id'), table_name='remote_service')
    op.drop_table('remote_service')
    # ### end Alembic commands ###
