"""Refactor PSSR to Client and Machine fields

Revision ID: 46619500fe29
Revises: 579c6e95c1a5
Create Date: 2026-02-09 21:41:24.396454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46619500fe29'
down_revision: Union[str, None] = '579c6e95c1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
