"""Refactor PSSR to Client and Machine fields

Revision ID: 579c6e95c1a5
Revises: 665eabfeffbd
Create Date: 2026-02-09 21:40:06.323406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579c6e95c1a5'
down_revision: Union[str, None] = '665eabfeffbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('pssr', sa.String(), nullable=True))
    op.alter_column('clients', 'external_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_clients_name', table_name='clients')
    op.add_column('machines', sa.Column('last_visit', sa.String(), nullable=True))
    op.add_column('machines', sa.Column('next_visit', sa.String(), nullable=True))
    op.add_column('machines', sa.Column('psi_status', sa.String(), nullable=True))
    op.drop_column('pssr', 'compte')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pssr', sa.Column('compte', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('machines', 'psi_status')
    op.drop_column('machines', 'next_visit')
    op.drop_column('machines', 'last_visit')
    op.create_index('ix_clients_name', 'clients', ['name'], unique=False)
    op.alter_column('clients', 'external_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('clients', 'pssr')
    # ### end Alembic commands ###
