"""Add reference_number

Revision ID: 6357392de6c9
Revises: 5f89fba64d98
Create Date: 2026-02-10 20:46:28.375465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6357392de6c9'
down_revision: Union[str, None] = '5f89fba64d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suivi_ps', sa.Column('reference_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suivi_ps', 'reference_number')
    # ### end Alembic commands ###
