"""Add PSSR SuiviPS InspectionRate tables

Revision ID: 665eabfeffbd
Revises: c49df3ed0b4d
Create Date: 2026-02-09 21:29:03.106261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665eabfeffbd'
down_revision: Union[str, None] = 'c49df3ed0b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('or_segment', sa.String(), nullable=True),
    sa.Column('type_materiel', sa.String(), nullable=True),
    sa.Column('atelier', sa.String(), nullable=True),
    sa.Column('date_facture', sa.String(), nullable=True),
    sa.Column('last_inspect', sa.String(), nullable=True),
    sa.Column('nbr', sa.Integer(), nullable=True),
    sa.Column('nom_client_or', sa.String(), nullable=True),
    sa.Column('is_inspected', sa.String(), nullable=True),
    sa.Column('technicien_reel', sa.String(), nullable=True),
    sa.Column('equipe_reelle', sa.String(), nullable=True),
    sa.Column('temps_reel', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['machines.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_rate_id'), 'inspection_rate', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_rate_serial_number'), 'inspection_rate', ['serial_number'], unique=False)
    op.create_table('pssr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('compte', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('ville', sa.String(), nullable=True),
    sa.Column('famille', sa.String(), nullable=True),
    sa.Column('modele', sa.String(), nullable=True),
    sa.Column('dernier_rapport', sa.String(), nullable=True),
    sa.Column('derniere_visite', sa.String(), nullable=True),
    sa.Column('prochaine_visite', sa.String(), nullable=True),
    sa.Column('retard_jours', sa.Integer(), nullable=True),
    sa.Column('inspecteur', sa.String(), nullable=True),
    sa.Column('commentaire', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['machines.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pssr_id'), 'pssr', ['id'], unique=False)
    op.create_index(op.f('ix_pssr_serial_number'), 'pssr', ['serial_number'], unique=False)
    op.create_table('suivi_ps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('ps_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('action_required', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['machines.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suivi_ps_id'), 'suivi_ps', ['id'], unique=False)
    op.create_index(op.f('ix_suivi_ps_serial_number'), 'suivi_ps', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suivi_ps_serial_number'), table_name='suivi_ps')
    op.drop_index(op.f('ix_suivi_ps_id'), table_name='suivi_ps')
    op.drop_table('suivi_ps')
    op.drop_index(op.f('ix_pssr_serial_number'), table_name='pssr')
    op.drop_index(op.f('ix_pssr_id'), table_name='pssr')
    op.drop_table('pssr')
    op.drop_index(op.f('ix_inspection_rate_serial_number'), table_name='inspection_rate')
    op.drop_index(op.f('ix_inspection_rate_id'), table_name='inspection_rate')
    op.drop_table('inspection_rate')
    # ### end Alembic commands ###
