"""Add CVAF table

Revision ID: c49df3ed0b4d
Revises: d4b9f7506a84
Create Date: 2026-02-09 21:11:04.742635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49df3ed0b4d'
down_revision: Union[str, None] = 'd4b9f7506a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cvaf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('cva_type', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('product_vertical', sa.String(), nullable=True),
    sa.Column('dlr_cust_nm', sa.String(), nullable=True),
    sa.Column('current_asset_age', sa.Integer(), nullable=True),
    sa.Column('asset_age_group', sa.String(), nullable=True),
    sa.Column('inspection_score', sa.String(), nullable=True),
    sa.Column('connectivity_score', sa.String(), nullable=True),
    sa.Column('sos_score', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['serial_number'], ['machines.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cvaf_id'), 'cvaf', ['id'], unique=False)
    op.create_index(op.f('ix_cvaf_serial_number'), 'cvaf', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cvaf_serial_number'), table_name='cvaf')
    op.drop_index(op.f('ix_cvaf_id'), table_name='cvaf')
    op.drop_table('cvaf')
    # ### end Alembic commands ###
